server.port=8000
spring.application.name=Meru-Config-Server
spring.cloud.config.server.git.uri=D:/Satish/Technical/Microservices/Batch 10/Implementation/Meru_Implementation/Meru-ConfigServer
eureka.client.service-url.defaltZone=http://localhost:8761/eureka
#Verify any repository issue in service startup
spring.cloud.config.server.git.cloneOnStart=true


