filename=meru-config-zuulserverr
server.port=8001
spring.application.name=meru-zuul-gateway
management.security.enabled=false
eureka.client.fetch-registry=true
#eureka.client.service-url.defaltZone=http://192.168.56.104:8761/eureka
eureka.client.service-url.defaltZone=http://localhost:8761/eureka
#eureka.client.service-url.defaltZone=http://172.17.0.3:8761/eureka
zuul.prefix=/api

zuul.routes.productview.path=/productview/**
zuul.routes.productview.service-id=meru-productview

zuul.routes.price.path=/price/**
zuul.routes.price.service-id=meru-price

zuul.routes.inventory.path=/inventory/**
zuul.routes.inventory.service-id=meru-inventory

zuul.routes.promotion.path=/promotion/**
zuul.routes.promotion.service-id=meru-promotion

