insert into INVENTORY(ID,PRODUCTID,INVENTORY) values (1,1,10);
insert into INVENTORY(ID,PRODUCTID,INVENTORY) values (2,2,11);
insert into INVENTORY(ID,PRODUCTID,INVENTORY) values (3,3,12);
insert into INVENTORY(ID,PRODUCTID,INVENTORY) values (4,4,13);
insert into INVENTORY(ID,PRODUCTID,INVENTORY) values (5,5,14);
